import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'

const font = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Felina',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body className={font.className}>
        <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange>

        {children}
        </ThemeProvider>
      </body>
    </html>
  )
}